<?php
namespace SRAG\ILIAS\Plugins\MetaData\Field;

use SRAG\ILIAS\Plugins\MetaData\Storage\DateTimeStorage;

/**
 * Class DateTimeField
 *
 * @author Stefan Wanzenried <sw@studer-raimann.ch>
 * @package SRAG\ILIAS\Plugins\MetaData\Field
 */
class DateTimeField extends Field
{

    /**
     * @inheritdoc
     */
    public function getStorage()
    {
        return new DateTimeStorage();
    }


    public function getCompatibleInputfields()
    {
        return array('SRAG\\ILIAS\\Plugins\\MetaData\\Inputfield\\InputfieldDateTime');
    }


    /**
     * @return DateTimeFieldOptions
     */
    public function options()
    {
        return parent::options(); // TODO: Change the autogenerated stub
    }


    /**
     * @inheritdoc
     */
    protected function getFieldOptions(array $data)
    {
        return new DateTimeFieldOptions($data);
    }
}