<?php

namespace SRAG\ILIAS\Plugins\MetaData\Field;

use SRAG\ILIAS\Plugins\MetaData\Storage\FloatStorage;

/**
 * Class FloatField
 *
 * @author  Stefan Wanzenried <sw@studer-raimann.ch>
 * @package SRAG\ILIAS\Plugins\MetaData\Field
 */
class FloatField extends Field
{

    /**
     * @return FloatFieldOptions
     */
    public function options()
    {
        return parent::options(); // TODO: Change the autogenerated stub
    }


    /**
     * @inheritdoc
     */
    public function getStorage()
    {
        return new FloatStorage();
    }


    public function getCompatibleInputfields()
    {
        return array('SRAG\\ILIAS\\Plugins\\MetaData\\Inputfield\\InputfieldFloat');
    }


    /**
     * @inheritdoc
     */
    protected function getFieldOptions(array $data)
    {
        return new FloatFieldOptions($data);
    }
}